# This is an example configuration file for the connect server
# Copy this file to config.yaml and modify it to suit your needs.

# HTTP server configuration
http:

  # The URL of the backend
  backend_url: 'http://localhost:8080'

  # The IPv4 address to bind the HTTP server to
  ipv4_host: '0.0.0.0' # 0.0.0.0 = all interfaces

  # The IPv6 address to bind the HTTP server to
  ipv6_host: '::' # :: = all interfaces

  # The port to bind the HTTP server to, both IPv4 and IPv6 share the same port
  port: 8080

  # Sets Gin's trusted proxies. This is useful when you have a reverse proxy in front of your application that sets the X-Forwarded-For header.
  # This is a list of IP addresses or CIDR ranges that are trusted proxies.
  trusted_proxies: []

  # Sets which hosts are allowed by CORS. This is a list of hostnames or IP addresses.
  cors_hosts: []

  # OpenTelemetry configuration
  tracing:

    # Enable OpenTelemetry tracing
    enabled: false

    # The OpenTelemetry collector endpoint
    otlp_endpoint: ''

  # Golang pprof configuration
  pprof:

    # Enable Golang pprof
    enabled: false

  # Prometheus metrics configuration
  metrics:

    # Enable Prometheus metrics
    enabled: false

    # The IPv4 address to bind the Prometheus metrics server to
    ipv4_host: '127.0.0.1' # 127.0.0.1 = localhost

    # The IPv6 address to bind the Prometheus metrics server to
    ipv6_host: '::1' # ::1 = localhost

    # The port to bind the Prometheus metrics server to, both IPv4 and IPv6 share the same port
    port: 8081

# Persistence configuration
persistence:
  # Database configuration
  database:
    driver: 'sqlite' # sqlite, mysql, postgres
    database: 'rtz.sqlite3' # Path to the SQLite3 database file or database name for other drivers
    # host: 'localhost' # Hostname of the database server
    # port: 3306 # Port of the database server
    # username: 'root' # Username to connect to the database server
    # password: '' # Password to connect to the database server
    # extra_parameters: '' # Extra parameters to pass to the database driver
  # Path where upload files are stored
  uploads: 'uploads/'

# User registration configuration
registration:
  # Enable user registration
  enabled: false

auth:
  google:
    client_id: ''
    client_secret: ''
  github:
    client_id: ''
    client_secret: ''

jwt:
  secret: 'secret'

mapbox:
  public_token: 'changeme'
  secret_token: 'changeme'